# Generated by Django 4.1.5 on 2023-02-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_comment_commented_by_alter_comment_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='archive',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
